### ISSUE TITLE
No referencing possible to SpriteDicing.DicedSpriteAtlas

### ISSUE THREAD

**Issue by Helvest** [elringus/sprite-dicing#45]
Hello,

I am encountering an issue with the Elringus.SpriteDicing.Runtime.asmdef file. Currently, the option "Auto Referenced" is on false by default, which prevents me from referencing SpriteDicing.DicedSpriteAtlas elsewhere in my code.

I would like to know if it is possible to change this to true by default or if there is an reason why it is set up this way.

Thank you for your assistance.

**Comment by elringus** [comment]
Hi, It's disabled to prevent unnecessary overhead in compile times when you don't need to access the API. This is considered the best practice for most Unity extensions.

To access the API, keep your own code under an asmdef and explicitly reference SpriteDicing.

**Comment by Helvest** [comment]
Ok, thank you
